Ex 16275 Snowflake Connector (#228)
* EX-16275 Added snowflake settings to settings file, this assumes variables are added into environment

* Revert "EX-16275 Added snowflake settings to settings file, this assumes variables are added into environment"

This reverts commit 626b18b800a57c9b575e84e2f35395d585cb2938.

* EX-16275 Adding core settings

Added Snowflake environment variables.

* EX-16275 Add snowflake db connector

Added snowflake connector

* EX-16275 explicit return

Added explicit return for clarity

* EX-16275 Added explicit return

* Modified the connector for testing

* Added Debugging code

* Added debugging code

* Modified for multiple connectors

* Code to select Snowflake connector

* Minor formatting

* Changed to handle multiple connectors

* Modified test for Snowflake

* Modified for Snowflake

* Debugging notes

* Added Snowflake option

* Moved  _check_tables_exist to abstract class

* Remove commented out code

* Removed commented out code

Also removed query to print out

* Tidy up cryptography import

* Logger level

changed from info to debug

* Removed debugging code

* Added cryptography library

* Tidied code (as per ruff)

 Removed various duplicate imports and comments:
1. Commented out  F841 Local variable `datasource_db_snowflake_warehouse` is assigned to but never used
2. src/hutch_bunny/core/db/snowflake.py:1:8: F401 [*] `snowflake.connector` imported but unused === commented out
3. src/hutch_bunny/core/db/snowflake.py:224:22: F541 [*] f-string without any placeholders === removed
4. src/hutch_bunny/core/db/snowflake.py:255:21: F541 [*] f-string without any placeholders===removed
5. src/hutch_bunny/core/settings.py:1:45: F401 [*] `pydantic_settings.SettingsConfigDict` imported but unused===removed
6. src/hutch_bunny/core/solvers/availability_solver.py:31:45: F401 [*] `hutch_bunny.core.logger.INFO` imported but unused===commented out
7. tests/conftest.py:7:33: F401 [*] `hutch_bunny.core.db.SyncDBClient` imported but unused===removed
8. tests/conftest.py:14:31: F811 [*] Redefinition of unused `db` from line 3===commented
9. tests/conftest.py:14:31: F401 [*] `hutch_bunny.core.db` imported but unused===removed
10. tests/integration/test_code_distribution_query.py:14:31: F811 [*] Redefinition of unused `db` from line 13===Commented out
11. tests/integration/test_code_distribution_query.py:15:51: F401 [*] `hutch_bunny.core.rquest_models.cohort.Cohort`===commented out
12. tests/integration/test_code_distribution_query.py:16:50: F401 [*]‎ = ==commented out
13. tests/integration/test_code_distribution_query.py:17:49: F401 [*] ‎ = ==commented out
14. tests/integration/test_code_distribution_query.py:18:33: F811 [*] Redefinition of unused `SyncDBClient===commented out
15. tests/integration/test_code_distribution_query.py:20:5: F811 [*] Redefinition of unused `DistributionQuery`===commented out
16. tests/integration/test_code_distribution_query.py:21:5: F811 [*] Redefinition of unused `DistributionQueryType` from line 7===commented out
17. tests/integration/test_code_distribution_query.py:23:57: F401 [*] `hutch_bunny.core.rquest_models.availability.AvailabilityQuery===commented out
18. tests/integration/test_code_distribution_query.py:24:39: F811 [*] Redefinition of unused `Settings` from line 12===commented out
19. tests/integration/test_code_distribution_query.py:25:31: F811 [*] Redefinition of unused `db` from line 14===commentedout

* Auto stash before merge of "EX-16275-Snowflake_update" and "origin/EX-16275-Snowflake_update"

* Update src/hutch_bunny/core/settings.py

Co-authored-by: Andy Rae <1127507+AndyRae@users.noreply.github.com>

* Delete .env_snowflake2

* Delete .DS_Store

* Delete .env_snowflake

* Delete src/hutch_bunny/.DS_Store

* Delete src/.DS_Store

* Added snowflake dependency

* Delete .idea directory

remove pycharm code

---------

Co-authored-by: Andy Rae <1127507+AndyRae@users.noreply.github.com>